# Generated by Django 3.1.3 on 2022-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220319_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='닉네임', max_length=20),
        ),
    ]
